const db = require('../database'); // importing the SQLite database instance. Allowing interaction with it and performing CRUD ops

// getHabits retrieves all habits for the authenticated user. 
// uses userID from the JWT token (set by verifyToken middleware) to query the database for habits that belong to that user.
exports.getHabits = (req, res) => {
  const userId = req.userId; // here is the userID.

  // Here is the query to get all habits for the user. all has the structure: all(query, params, callback).
  db.all(
    'SELECT id, name, category, description, createdAt FROM habits WHERE userId = ? ORDER BY createdAt DESC',
    [userId],

    // here's the callback function. Handles the response from the query. If there's an error, sends 500 status with error.
    (err, habits) => {
      if (err) {
        return res.status(500).json({ error: 'Database error' });
      }
      res.json(habits); // then sends the habits as a JSON response. This will be an array of habit objects that belong to the authenticated user.
    }
  );
};

// now, createHabit, deleteHabit and updateHabit are defined below. They all follow a similar pattern:
// 1. Get userId from req.userId (set by verifyToken middleware).
// 2. Perform necessary validation on the input data.
// 3. Interact with the database to create, delete or update a habit.
// 4. Handle errors and send appropriate JSON responses back to the client.
exports.createHabit = (req, res) => {
  const userId = req.userId; // we are saying "get userID from the req object, pass it to the variable userID". 
  const { name, category, description } = req.body; // again, saying "get name, category and desc from the 'body' of the req, pass them to the variables 
  // name, category and description". 
  // req.body is where the incoming JSON data from the client is stored after being parsed by express.json() middleware in server.js. so it's in the json format.

  // although we could have checked for category and description, they are optional fields, so we only check for name.
  if (!name) {
    return res.status(400).json({ error: 'Habit name is required' });
  }

  // now we run the query to insert a new habit into the database. 
  // the structure of db.run is db.run(query, params, callback). 
  // similar to db.all, but used for insert/update/delete operations. 
  // the callback here will handle the response after trying to insert the habit. 
  // if there's an error, it sends a 500 status with an error message. 
  // if successful, it sends a 201 status with the details of the newly created habit (including the id generated by the database).
  db.run(
    'INSERT INTO habits (userId, name, category, description) VALUES (?, ?, ?, ?)',
    [userId, name, category || 'general', description || null],
    function (err) {
      if (err) {
        return res.status(500).json({ error: 'Database error' });
      }
      res.status(201).json({ id: this.lastID, name, category, description });
    }
  );
};

// deleteHabit. This function deletes a habit by its ID, but only if it belongs to the authenticated user.
exports.deleteHabit = (req, res) => {
  const userId = req.userId;
  const habitId = req.params.id; // we're saying "get the id from the URL parameters (e.g., /api/habits/:id), pass it to the variable habitId". so this may have something like 
  // "/1" or "/2" depending on which habit we want to delete.

  // db.get is used to check if the habit exists and belongs to the user before attempting to delete it. 
  // This is important for security, to ensure that users can only delete their own habits. 
  // If the habit doesn't exist or doesn't belong to the user, it sends a 404 Not Found response. 
  // If it does exist and belongs to the user, it proceeds to delete it from the database.
  db.get('SELECT id FROM habits WHERE id = ? AND userId = ?', [habitId, userId], (err, habit) => {
    if (err) {
      return res.status(500).json({ error: 'Database error' });
    }

    if (!habit) {
      return res.status(404).json({ error: 'Habit not found' });
    }

    // after the checks, we run the delete query.
    db.run('DELETE FROM habits WHERE id = ?', [habitId], (err) => {
      if (err) {
        return res.status(500).json({ error: 'Database error' });
      }
      res.json({ message: 'Habit deleted' }); // if successful, it sends a JSON response with a success message.
    });
  });
};

// updating habits. 
exports.updateHabit = (req, res) => {
  const userId = req.userId; // get userId from req.userId, set by verifyToken middleware.
  const habitId = req.params.id; // get habitId from URL parameters (e.g., /api/habits/:id). This identifies which habit we want to update. again, habitID may 
  // have something like "/1" or "/2" depending on which habit we want to update.
  const { name, category, description } = req.body; // get the updated name, category and description from the request body. 
  // this is the new data we want to update the habit with. concrete value examples would be 
  // "name: 'Go to the gym', category: 'fitness', description: 'Go to the gym 3 times a week'".


  // similar to deleteHabit, we first check if the habit exists and belongs to the user before attempting to update it.
  db.get('SELECT id FROM habits WHERE id = ? AND userId = ?', [habitId, userId], (err, habit) => {
    if (err) {
      return res.status(500).json({ error: 'Database error' });
    }

    if (!habit) {
      return res.status(404).json({ error: 'Habit not found' });
    }

    // again, running db.run to execute the update query. We set the name, category and description to the new values provided in the request body.
    db.run(
      'UPDATE habits SET name = ?, category = ?, description = ? WHERE id = ?',
      [name || null, category || null, description || null, habitId], // we're saying
      //  "if name is provided, use it; otherwise, set it to null. 
      // same for category and description". 
      // this allows partial updates where the client can send only the fields they want to update. 
      (err) => {
        if (err) {
          return res.status(500).json({ error: 'Database error' });
        }
        res.json({ message: 'Habit updated' });
      }
    );
  });
};
